### ISSUE TITLE
You can go back to the repository

### ISSUE THREAD

**Issue by AndrioJonatas** [Fancy2209/Wii-Mod#1]
You can go back to the repository: https://github.com/Fancy2209/wiimotevr - Please?

**Comment by Fancy2209** [comment]
> You can go back to the repository: https://github.com/Fancy2209/wiimotevr - Please?
> 

That was something I tough about doing but realized I didn't know enough to do
Not enough of a dev for that yet

**Comment by Fancy2209** [comment]
Maybe I will at some point but I just had no idea what i was doing in that one, need to actually learn C++ first (i don't know how I actually understood how to do this celeste mod)
It's also no futile task getting a 3DOF Device on the 6DOF world 
Maybe someday, but don't get your hopes up

**Comment by AndrioJonatas** [comment]
> Talvez eu vá em algum momento, mas eu simplesmente não tinha ideia do que estava fazendo naquele, preciso realmente aprender C++ primeiro (não sei como realmente entendi como fazer esse mod celeste) Também não é uma tarefa fútil obter um Dispositivo 3DOF no mundo 6DOF Talvez um dia, mas não tenha muitas esperanças

For me it's useful to leave it released please or send the files.

**Comment by Fancy2209** [comment]
> > Talvez eu vá em algum momento, mas eu simplesmente não tinha ideia do que estava fazendo naquele, preciso realmente aprender C++ primeiro (não sei como realmente entendi como fazer esse mod celeste) Também não é uma tarefa fútil obter um Dispositivo 3DOF no mundo 6DOF Talvez um dia, mas não tenha muitas esperanças
> 
> For me it's useful to leave it released please or send the files.

Bem.
Mas tudo o que eu tinha feito era fazer fork de outro projeto para Joy cons.
Então, qual é a diferença?
